Repository neozhu/CleanArchitectureWithBlazorServer, pull requests merged in 2023-05, with the labels that each got.

#377 Updated README
  README.md
Labels: documentation

#379 Support UtcTimestamp for serilog
  src/Domain/Entities/Logger/Logger.cs
  src/Infrastructure/Extensions/SerilogExtensions.cs
Labels: enhancement

#380 Timezone conversions
  .editorconfig
  src/Application/Features/Loggers/DTOs/LogDto.cs
  src/Blazor.Server.UI/Blazor.Server.UI.csproj
  src/Blazor.Server.UI/Pages/SystemManagement/Logs.razor
  src/Blazor.Server.UI/Pages/_Layout.cshtml
  src/Blazor.Server.UI/_Imports.razor
  src/Infrastructure/Services/DateTimeService.cs
Labels: enhancement, help wanted

#390 Fixed: Nullable boolean to boolean
  src/Blazor.Server.UI/Pages/Identity/Users/_UserForm.razor
Labels: bug

#392 Privacy feature for logging client information
  src/Application/Common/Configurations/PrivacySettings.cs
  src/Blazor.Server.UI/appsettings.json
  src/Infrastructure/Extensions/SerilogExtensions.cs
Labels: enhancement

#394 Added Configuration Documentation
  src/Application/Common/Configurations/AppConfigurationSettings.cs
  src/Application/Common/Configurations/DashbordSettings.cs
  src/Application/Common/Configurations/DatabaseSettings.cs
  src/Application/Common/Configurations/PrivacySettings.cs
  src/Blazor.Server.UI/appsettings.json
  src/Infrastructure/DependencyInjection.cs
  src/Infrastructure/Extensions/SerilogExtensions.cs
Labels: documentation
