Repository neozhu/CleanArchitectureWithBlazorServer, pull requests merged in 2023-07, with the labels that each got.

#442 🎨 art(Application): username and rolename set constants string
  .github/workflows/codeql.yml
  CleanArchitecture.Blazor.nuspec
  CleanArchitecture.Blazor.sln
  src/Application/Constants/Role/RoleNameConstants.cs
  src/Application/Constants/User/UserNameConstants.cs
  src/Blazor.Server.UI/Services/Navigation/MenuService.cs
  src/Infrastructure/Constants/User/UserNameConstants.cs
  src/Infrastructure/Persistence/ApplicationDbContextInitializer.cs
Labels: Enhancement

#447 ♻️ recycle(Infrastructure): Switch events dispatcher to interceptor.
  src/Infrastructure/DependencyInjection.cs
  src/Infrastructure/Extensions/MediatorExtensions.cs
  src/Infrastructure/Persistence/ApplicationDbContext.cs
  src/Infrastructure/Persistence/Interceptors/AuditableEntityInterceptor.cs
  src/Infrastructure/Persistence/Interceptors/DispatchDomainEventsInterceptor.cs
Labels: Enhancement

#452 Added: Google Analytics Configurator
  CleanArchitecture.Blazor.nuspec
  src/Application/Common/Configurations/PrivacySettings.cs
  src/Blazor.Server.UI/ConfigureServices.cs
  src/Blazor.Server.UI/Program.cs
  src/Blazor.Server.UI/appsettings.json
Labels: Enhancement

#453 Minor spelling improvements to the readme
  README.md
Labels: Documentation, Refactoring

#454 Restore Logging of Client Agents: Fix for Breaking Change in Serilog.Enrichers.ClientInfo v2.0.0
  src/Infrastructure/Extensions/SerilogExtensions.cs
Labels: Bug, Enhancement
